# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sonatype/nexus3
  tag: 3.15.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

persistence:
  storage: 10Gi
  storageClass: null
  accessModes: [ReadWriteOnce]

env:
  - name: INSTALL4J_ADD_VM_PARAMS
    value: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
  - name: NEXUS_CONTEXT
    value: "nexus"

contextPath: nexus
port: 8081

livenessProbe:
  initialDelaySeconds: 180

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   limits:
#    memory: 2Gi
#   requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
