# Default values for redis-cluster-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: redis
  tag: 5.0.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

usePassword: true
password: null
clusterReplicas: 1

persistence:
  storage: 10Gi
  storageClass: null
  accessModes: [ReadWriteOnce]

service:
  type: ClusterIP
  port: 6379

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
   requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - redis-cluster
        topologyKey: kubernetes.io/hostname
