apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    helm.sh/chart: {{ include "redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: redis-health
data:
  ping_local.sh: |-
    response=$(
      redis-cli \
      -a $REDIS_PASSWORD \
      -h localhost \
      -p $REDIS_PORT \
      ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
