{{- if .Values.usePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app.kubernetes.io/name: {{ include "redis-cluster-helm.name" . }}
    helm.sh/chart: {{ include "redis-cluster-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.password }}
  redis-password: {{ .Values.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
