apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster-helm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-cluster-helm.name" . }}
    helm.sh/chart: {{ include "redis-cluster-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "redis-cluster-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
