replicaCount: 1

image:
  repository: redis
  tag: 5.0.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
usePassword: true
password: null

persistence:
  storage: 10Gi
  storageClass: null
  accessModes: [ReadWriteOnce]

service:
  type: ClusterIP
  port: 6379

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
   requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
